/**
 * <br>
 * Represents a habit category within the Habit Builder application. Categories
 * are used to group habits into meaningful classifications such as “Health,”
 * “Fitness,” “Productivity,” etc.
 * <br><br>
 *
 * This entity is stored in the Room database table defined by
 * {@link HabitBuilderDatabase#CATEGORIES_TABLE}. Each category is assigned
 * an auto-generated primary key and contains a user-friendly name.
 * <br><br>
 *
 * <b>Authors:</b> Bryan, Lee, Alexander <br>
 * <b>Course:</b> CST 338 – Software Design <br>
 * <b>Semester:</b> Fall 2025 <br>
 * <b>Last Updated:</b> 12/18/2025
 */
        package com.example.cst338_f25b_group2_project02.database.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.cst338_f25b_group2_project02.database.HabitBuilderDatabase;

import java.util.Objects;

/**
 * Entity class for representing a habit category. Each category has an auto-generated
 * ID and a descriptive name that can be assigned to one or more habits.
 */
@Entity(tableName = HabitBuilderDatabase.CATEGORIES_TABLE)
public class Categories {

    /**
     * Unique identifier for the category, auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    private int categoryId;

    /**
     * The readable name of the category (e.g., "Health", "Fitness").
     */
    private String categoryName;

    /**
     * Constructs a new {@code Categories} instance with the provided category name.
     *
     * @param categoryName the name assigned to this category
     */
    public Categories(String categoryName) {
        this.categoryName = categoryName;
    }

    // ------------------- Getters -------------------

    /**
     * Returns the unique ID of the category.
     *
     * @return the category's ID
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * Returns the readable name of the category.
     *
     * @return the category name
     */
    public String getCategoryName() {
        return categoryName;
    }

    // ------------------- Setters -------------------

    /**
     * Sets the unique ID for the category. Normally called internally by Room.
     *
     * @param categoryId the new ID for the category
     */
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Updates the name of the category.
     *
     * @param categoryName the new readable category name
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    // ------------------- Equality -------------------

    /**
     * Compares this {@code Categories} instance to another object for equality.
     * Two categories are equal if they share the same ID and name.
     *
     * @param o the object to compare to
     * @return {@code true} if the objects represent the same category
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Categories that = (Categories) o;
        return categoryId == that.categoryId &&
                Objects.equals(categoryName, that.categoryName);
    }

    /**
     * Computes a hash code based on the category's ID and name.
     *
     * @return a hash code value for this category
     */
    @Override
    public int hashCode() {
        return Objects.hash(categoryId, categoryName);
    }
}
