/**
 * <br>
 * Represents a single log entry for a habit on a given date within the Habit Builder
 * application. Habit logs track whether a user has completed a habit for a specific
 * day, enabling features such as daily checklists, progress tracking, and habit
 * completion streaks.
 * <br><br>
 *
 * This entity is stored in the Room database table defined by
 * {@link HabitBuilderDatabase#HABIT_LOGS_TABLE}. Each log entry is assigned an
 * auto-generated primary key and contains references to the associated habit,
 * the owning user, the date of the log, and whether the habit was completed.
 * <br><br>
 *
 * <b>Authors:</b> Bryan, Lee, Alexander <br>
 * <b>Course:</b> CST 338 – Software Design <br>
 * <b>Semester:</b> Fall 2025 <br>
 * <b>Last Updated:</b> 12/18/2025
 */
        package com.example.cst338_f25b_group2_project02.database.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.cst338_f25b_group2_project02.database.HabitBuilderDatabase;

import java.util.Objects;

/**
 * Entity class that models a habit log, representing a user's completion status
 * for a specific habit on a particular date.
 */
@Entity(tableName = HabitBuilderDatabase.HABIT_LOGS_TABLE)
public class HabitLogs {

    /**
     * Unique identifier for this log entry, auto-generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    private int logId;

    /**
     * The ID of the habit this log entry is associated with.
     */
    private int habitId;

    /**
     * The ID of the user who owns this habit and log entry.
     */
    private int userId;

    /**
     * The date for which this log entry applies, stored as a string in ISO format (YYYY-MM-DD).
     */
    private String date;

    /**
     * Indicates whether the habit was completed on this specific date.
     */
    private boolean isCompleted;

    /**
     * Constructs a new habit log entry.
     *
     * @param habitId     the ID of the associated habit
     * @param userId      the ID of the user who performed the habit
     * @param date        the date of this log entry (ISO string format)
     * @param isCompleted {@code true} if the habit was completed on this date; {@code false} otherwise
     */
    public HabitLogs(int habitId, int userId, String date, boolean isCompleted) {
        this.habitId = habitId;
        this.userId = userId;
        this.date = date;
        this.isCompleted = isCompleted;
    }

    // ------------------- Getters -------------------

    /**
     * Returns the unique log ID for this entry.
     *
     * @return the log entry’s ID
     */
    public int getLogId() { return logId; }

    /**
     * Returns the ID of the habit associated with this log entry.
     *
     * @return the habit ID
     */
    public int getHabitId() { return habitId; }

    /**
     * Returns the ID of the user who owns this log entry.
     *
     * @return the user ID
     */
    public int getUserId() { return userId; }

    /**
     * Returns the date this log entry represents.
     *
     * @return the log date in ISO string format
     */
    public String getDate() { return date; }

    /**
     * Returns whether the habit was completed on this log's date.
     *
     * @return {@code true} if completed; {@code false} otherwise
     */
    public boolean isCompleted() { return isCompleted; }

    // ------------------- Setters -------------------

    /**
     * Sets the log ID (normally assigned by Room during insertion).
     *
     * @param logId the new log ID
     */
    public void setLogId(int logId) { this.logId = logId; }

    /**
     * Updates the habit ID associated with this log entry.
     *
     * @param habitId the new habit ID
     */
    public void setHabitId(int habitId) { this.habitId = habitId; }

    /**
     * Updates the user ID associated with this log entry.
     *
     * @param userId the new user ID
     */
    public void setUserId(int userId) { this.userId = userId; }

    /**
     * Updates the date of this log entry.
     *
     * @param date the new date (ISO string)
     */
    public void setDate(String date) { this.date = date; }

    /**
     * Sets whether the habit was completed on this log's date.
     *
     * @param completed the completion state
     */
    public void setCompleted(boolean completed) { isCompleted = completed; }

    // ------------------- Equality -------------------

    /**
     * Compares this log to another for equality. Two log entries are equal if all
     * fields including IDs, habit reference, user reference, date, and completion
     * state match.
     *
     * @param o the object to compare to
     * @return {@code true} if the objects represent the same log entry
     */
    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        HabitLogs habitLogs = (HabitLogs) o;
        return logId == habitLogs.logId &&
                habitId == habitLogs.habitId &&
                userId == habitLogs.userId &&
                isCompleted == habitLogs.isCompleted &&
                Objects.equals(date, habitLogs.date);
    }

    /**
     * Computes a hash code based on all fields in this log entry.
     *
     * @return the calculated hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(logId, habitId, userId, date, isCompleted);
    }
}
